### ISSUE TITLE
Crash- rendering screen

### ISSUE THREAD

**Issue by Alessandro404** [DaedalusGame/RequiousFrakto#1]
Hi! Well I guess I'm the first. 
I want to tell you man. This mod can be the best thing ever.  

It crashes on me.

Using forge, the last version disponible for 1.12.2
Also, the machines included don't have a localized name.

this crash is with no other mods. 
[crash-2019-08-21_21.53.55-client.txt](https://github.com/DaedalusGame/RequiousFrakto/files/3527071/crash-2019-08-21_21.53.55-client.txt)

**Comment by Alessandro404** [comment]
I should add. I have the same crash with crafttweaker too, and an error from loading .zs script that I don't really understand.

I'm not really sure, but the machine jsons were automatically added with the mod installation, but not the scripts, so I've pasted machines.zs in my script folder. 

Here the error with my modpack and the error of crafttweaker from good measure.
Hope for this to be useful.
[crash-2019-08-21_22.12.24-client.txt](https://github.com/DaedalusGame/RequiousFrakto/files/3527181/crash-2019-08-21_22.12.24-client.txt)
[ctlog.txt](https://github.com/DaedalusGame/RequiousFrakto/files/3527182/ctlog.txt)

**Comment by DaedalusGame** [comment]
Fixed the crash issue, not sure about the CT issue but if it's still a problem open another issue
