### ISSUE TITLE
Random Output Support

### ISSUE THREAD

**Issue by Realme23** [DaedalusGame/RequiousFrakto#20]
Add support for random (chance-based) outputs. For example, 
RecipeContainer::addItemOutput(String group, IItemStack item, float chance)
where chance is a number from 0 to 1 or 0 to 100

**Comment by DaedalusGame** [comment]
already exists, you can get an instance of `mods.requious.Random` from the recipe container (thats the parameter of your recipe function), which lets you get random numbers. Take a look at [this](https://github.com/DaedalusGame/The-Testbed/blob/69aa2a4c7202268a5b369349bd078308637f5bc4/scripts/fuel_processor.zs#L56-L63)
